### PR TITLE
fixes https://github.com/jazzband/django-eav2/issues/163

### LINKED ISSUE #163: django.core.exceptions.FieldError raised when filtering on foreign key
When attempting a reverse filter using a foreign key on model registered with eav, a django core exception is (django.core.exceptions.FieldError: Related Field got invalid lookup) raised.

## Expected Behavior
A filtered queryset should be returned.

## Actual Behavior
An exception is raised: django.core.exceptions.FieldError: Related Field got invalid lookup

## Possible Fix
Add try/except to the eav_filter function in queryset.py. I will create a pull request.

## Steps to Reproduce

1. Create two models and have the second model include a FK to the first:

```
class ModelOne(models.Model):
    name = models.CharField(max_length=16, blank=True, null=True, help_text='')


class ModelTwo(models.Model):
    name = models.CharField(max_length=16, blank=True, null=True, help_text='')
    one = models.ForeignKey(ModelOne, blank=True, null=True, on_delete=models.CASCADE, help_text='')
```

2. After making migrations and migrating, open a django shell, create a couple instances:

```
>>> ModelOne.objects.create()
>>> m1 = ModelOne.objects.create()
>>> ModelTwo.objects.create()
>>> ModelTwo.objects.create(one=m1)
```

3. Test filtering instances of the first model using the reverse relation:

```
>>> ModelOne.objects.filter(modeltwo=None)
<QuerySet [<ModelOne: ModelOne object (1)>]>
```

4. Add eav to the first model:

```
@register_eav()
class ModelOne(models.Model):
    name = models.CharField(max_length=16, blank=True, null=True, help_text='')
```

5. After making migrations and migrating, open a django shell and try the filter again:

```
>>> ModelOne.objects.filter(modeltwo=None)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/eav/queryset.py", line 187, in wrapper
    return func(self, *nargs, **nkwargs)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/eav/queryset.py", line 275, in filter
    return super(EavQuerySet, self).filter(*args, **kwargs)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/david/code/examples/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1184, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup:
```

## Your Environment
python 3.9.2
django 3.2.11
pip 21.1.2
ubunutu 21.04

### PR DESCRIPTION
**Pull request by davidslusser**
# I'm helping!
When attempting a reverse filter using a foreign key on model registered with eav, a django core exception is (django.core.exceptions.FieldError: Related Field got invalid lookup) raised. To address this I've added a try/except in the eav_filter function in queryset.py and return the original args and kwargs.

## Checklist
- [ x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc.)
- [ x] I have created at least one test case for the changes I have made

## Pull Request type
Please check the type of change your PR introduces:
- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related issue(s)
- Closes #163 

Example. Refs #
https://github.com/jazzband/django-eav2/issues/163

### CODE REVIEW

**Comment by Dresdn** [comment]
Thank you for the PR @davidslusser. I did tweak it a bit as the resulting filter caught my eye, so I fixed the underlying issue. Take a look and let me know if everything on your end is good with the fix and I'll get it pushed.

**Comment by Dresdn** [comment]
Interesting that there isn't a test for lines 260-262. I'll look more into this as I'm diving into parts of the code for the first time myself.

**Comment by davidslusser** [comment]
@Dresdn looks good to me; thanks for the fix!

**Comment by Dresdn** [comment]
Thanks @davidslusser. I pulled what seems to be stale code out from the Django 1.x days. I think I understand what's going on, but seems things were changed from 1.x to 2.x.

For future reference, the only test that hit the removed code was `tests.test_forms.test_m2m()`

**Pull request merged**
